stages:
    - pull

pull-job:
    stage: pull
    script:
        - cd /root/sdmanagementportal/
        - git checkout master
        - sudo git pull
        - source venv/bin/activate
        - python3 -m pip install -r requirements.txt
        - deactivate
        - sudo systemctl restart gunicorn
        - sudo cp /root/sdmanagementportal/configs/nginx.conf /etc/nginx/nginx.conf
        - sudo systemctl restart nginx
